[build]
  command = "npm run build"
  publishOrigin = "config"
  publish = "build"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true

[functions]
  directory = "netlify/functions"

[[plugins]]'
  origin = "config"
  package = "@netlify/plugin-nextjs"